# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  qdrant:
    container_name: testqdrant
    image: qdrant/qdrant:dev
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage
volumes:
  qdrant-storage:
